feat: Rename nonce verifiable to verification index
decentraland/contracts-commons pull request #25
Opened 2022-09-13 20:49 UTC by fzavalia

Closes #21

2022-09-13 23:07 UTC, nachomazzara commented on contracts/signatures/AssetNonceVerifiable.sol
> +abstract contract AssetVerificationIndex is ContextUpgradeable {
Why not `AssetIndexVerifiable`?

2022-09-13 23:11 UTC, nachomazzara commented on contracts/signatures/AssetNonceVerifiable.sol
> +    mapping(address => mapping(uint256 => mapping(address => uint256))) private assetVerificationIndex;
Is there any reason why you have named it that way instead of `assetIndex`?

2022-09-13 23:13 UTC, nachomazzara commented on contracts/signatures/AssetNonceVerifiable.sol
> +    event AssetVerificationIndexUpdated(
Same about keeping the previous name convention

2022-09-13 23:14 UTC, nachomazzara commented on contracts/signatures/AssetNonceVerifiable.sol
> +    function _bumpAssetVerificationIndex(
Is there any reason why you have named it that way instead of `_bumpAssetIndex`?

2022-09-13 23:18 UTC, nachomazzara requested changes
I left some messages but they apply to all the changes. I would like to understand if there is any reason why we didn't just change `asset` for `index`.

Example: 
- Instead of `AssetIndexVerifiable` we have `AssetVerificationIndex`
- Instead of `bumpAssetIndex` we have `bumpAssetVerificaitionindex`
- Instead of `assetNonce` we have `assetVerificationIndex`
etc

2022-09-15 15:36 UTC, fzavalia commented
@nachomazzara I was trying to give it a name that explains better what it does, however, it doesn't seem to be enough. 
At least just replacing Nonce with Index denotes a difference with nonces that are so commonly used in blockchain for other things

2022-09-15 17:50 UTC, fzavalia commented
Closing in favor of #26

2022-09-15 17:50 UTC, closed without merging